from threading import *
import time
def display():
    print(current_thread().name,'started')
    time.sleep(3)
    print(current_thread().name,'end')
t1=Thread(target=display,name='child thread 1')
t2=Thread(target=display,name='child thread 2')
t3=Thread(target=display,name='child thread 3')
t1.start()
t1.join()
t2.start()
t2.join()
t3.start()
l=enumerate()
for i in l:
    print('name',i.name())
time.sleep(10)
print("after 10 second of sleep")
print(t1.name,'is alive',t1.is_alive())
print(t2.name,'is alive',t2.is_alive())
print(t3.name,'is alive',t3.is_alive())
time.sleep(10)
print(t1.name,'is alive',t1.is_alive())
print(t2.name,'is alive',t2.is_alive())
print(t3.name,'is alive',t3.is_alive())